import { describe, it, expect } from 'vitest';
import {
  SCHEMA_VERSION,
  CLINICIAN_UID,
  PATIENT_UID,
  type KinePosePayload,
  type SessionResponse,
  type Envelope
} from '../../shared/src/index.js';
import path from 'node:path';
import { readFileSync, existsSync } from 'node:fs';
import {
  dispatchHealthRequest,
  dispatchSessionRequest,
  validateBootCredentials,
  CLIENT_DIR
} from './helpers/specHarness.js';

describe('Tier 3: Cross-Feature Interaction Test Suite', () => {
  // =========================================================================
  // INTERACTION 1: Clinician Creates Session -> Patient Joins Same Session
  // Features: F4 (Session Token Minting) x F5 (Deterministic User/Role Mapping)
  // =========================================================================

  it('T3-INT.1: Clinician creates session and Patient joins same session with matching sessionId and distinct UIDs', async () => {
    // Step 1: Clinician requests a new session without specifying sessionId
    const clinicianRes = await dispatchSessionRequest({ role: 'clinician' });
    expect(clinicianRes.status).toBe(200);

    const clinicianData: SessionResponse = clinicianRes.data;
    expect(clinicianData.uid).toBe(CLINICIAN_UID);
    expect(clinicianData.sessionId).toMatch(/^kine-/);
    expect(clinicianData.authToken).toBeTruthy();

    const sharedSessionId = clinicianData.sessionId;

    // Step 2: Patient joins using the sharedSessionId generated by clinician
    const patientRes = await dispatchSessionRequest({
      role: 'patient',
      sessionId: sharedSessionId
    });
    expect(patientRes.status).toBe(200);

    const patientData: SessionResponse = patientRes.data;
    expect(patientData.uid).toBe(PATIENT_UID);
    // Crucial check: both parties share the exact same sessionId
    expect(patientData.sessionId).toBe(sharedSessionId);
    expect(patientData.authToken).toBeTruthy();

    // Crucial check: roles and UIDs are strictly separated
    expect(clinicianData.uid).not.toBe(patientData.uid);
    expect(clinicianData.appId).toBe(patientData.appId);
    expect(clinicianData.region).toBe(patientData.region);
  });

  // =========================================================================
  // INTERACTION 2: Session ID & Telemetry Envelope Compatibility
  // Features: F2 (Shared Biomechanical Schemas) x F4 (Session Token Minting)
  // =========================================================================

  it('T3-INT.2: Telemetry envelope constructed with session response sessionId matches KinePosePayload schema', async () => {
    // Clinician initializes session
    const sessionRes = await dispatchSessionRequest({ role: 'clinician' });
    const { sessionId } = sessionRes.data;

    // Patient generates telemetry frame stamped with that sessionId
    const telemetryFrame: KinePosePayload = {
      v: SCHEMA_VERSION,
      sid: sessionId,
      t: Date.now(),
      type: 'kine.pose',
      seq: 1,
      fps: 30,
      phase: 'standing',
      kneeFlexionDeg: { L: 178.2, R: 179.0 },
      valgusDevPct: { L: 0.2, R: -0.1 },
      depthRatio: 0.02,
      vis: 0.99,
      reps: 0
    };

    // Verify envelope fields match session data
    expect(telemetryFrame.v).toBe(1);
    expect(telemetryFrame.sid).toBe(sessionId);
    expect(telemetryFrame.sid).toMatch(/^kine-/);
    expect(telemetryFrame.type).toBe('kine.pose');
    expect(typeof telemetryFrame.t).toBe('number');
  });

  // =========================================================================
  // INTERACTION 3: Health Probe and Concurrent Session Token Minting
  // Features: F3 (Health Probe) x F4 (Session Token Minting)
  // =========================================================================

  it('T3-INT.3: Health probe and session creation execute concurrently without interference', async () => {
    const [healthRes, sessionRes1, sessionRes2] = await Promise.all([
      dispatchHealthRequest(),
      dispatchSessionRequest({ role: 'clinician' }),
      dispatchSessionRequest({ role: 'patient' })
    ]);

    expect(healthRes.status).toBe(200);
    expect(healthRes.data.status).toBe('ok');

    expect(sessionRes1.status).toBe(200);
    expect(sessionRes1.data.uid).toBe('dr-demo');

    expect(sessionRes2.status).toBe(200);
    expect(sessionRes2.data.uid).toBe('pt-demo');

    // Both sessions generated independently have valid timestamps
    expect(sessionRes1.data.sessionId).toBeTruthy();
    expect(sessionRes2.data.sessionId).toBeTruthy();
  });

  // =========================================================================
  // INTERACTION 4: Boot Diagnostics & Session Lifecycle Resiliency
  // Features: F6 (Boot Credential Diagnostics) x F4 (Session Token Minting)
  // =========================================================================

  it('T3-INT.4: Diagnostic warning for truncated keys is emitted while session generation responds with valid structure', async () => {
    // Diagnostic check for truncated key
    const diag = validateBootCredentials({
      COMETCHAT_APP_ID: '168428446858f07fb',
      COMETCHAT_REGION: 'IN',
      COMETCHAT_AUTH_KEY: '1d33b8f1dc49d72eb92e20928a5cef60...'
    });

    expect(diag.isTruncated).toBe(true);
    expect(diag.warningMessage).toContain('truncated');

    // Server session endpoint remains responsive and handles request gracefully
    const sessionRes = await dispatchSessionRequest({ role: 'clinician' });
    expect(sessionRes.status).toBe(200);
    expect(sessionRes.data.sessionId).toBeTruthy();
  });

  // =========================================================================
  // INTERACTION 5: Vite Proxy Prefix Alignment with Express Endpoints
  // Features: F7 (Vite Proxy) x F3 (Health Probe) x F4 (Session API)
  // =========================================================================

  it('T3-INT.5: Vite proxy prefix /api maps 1:1 to Express endpoints /api/health and /api/session', () => {
    const proxyPrefix = '/api';
    const serverEndpoints = ['/api/health', '/api/session'];

    serverEndpoints.forEach(endpoint => {
      expect(endpoint.startsWith(proxyPrefix)).toBe(true);
      const subpath = endpoint.slice(proxyPrefix.length);
      expect(['/health', '/session']).toContain(subpath);
    });
  });

  // =========================================================================
  // INTERACTION 6: Envelope & Discriminated Union Message Routing
  // Features: F2 (Message Union) x F5 (User/Role Mapping)
  // =========================================================================

  it('T3-INT.6: Session marker payload synchronizes with clinician and patient demo UIDs', () => {
    const sessionMarker: Envelope & {
      type: 'kine.session';
      action: 'start';
      clinicianUid: string;
      patientUid: string;
    } = {
      v: SCHEMA_VERSION,
      sid: 'kine-active-session',
      t: Date.now(),
      type: 'kine.session',
      action: 'start',
      clinicianUid: CLINICIAN_UID,
      patientUid: PATIENT_UID
    };

    expect(sessionMarker.clinicianUid).toBe('dr-demo');
    expect(sessionMarker.patientUid).toBe('pt-demo');
    expect(sessionMarker.action).toBe('start');
  });

  // =========================================================================
  // INTERACTION 7: App Shell Session Input Keystroke Thrashing Elimination
  // =========================================================================

  it('T3-INT.7: App.tsx decouples sessionIdInput from active sessionId to eliminate WebRTC call thrashing on typing', () => {
    const appPath = path.join(CLIENT_DIR, 'src', 'App.tsx');
    expect(existsSync(appPath)).toBe(true);
    const appContent = readFileSync(appPath, 'utf8');

    // Ensure onChange only updates input state and does NOT directly invoke setSessionId
    const inputMatch = appContent.match(/id="session-id-input"[\s\S]*?\/>/);
    expect(inputMatch).not.toBeNull();
    const inputBlock = inputMatch![0];

    expect(inputBlock).toContain('setSessionIdInput(e.target.value)');
    expect(inputBlock).not.toContain('setSessionId(e.target.value');
    expect(inputBlock).toContain("e.key === 'Enter'");
  });

  // =========================================================================
  // INTERACTION 8: Patient Standalone Camera Fallback & Polarity Invariants
  // =========================================================================

  it('T3-INT.8: Patient.tsx implements standalone camera fallback and unmirrored valgus polarity', () => {
    const patientPath = path.join(CLIENT_DIR, 'src', 'views', 'Patient.tsx');
    expect(existsSync(patientPath)).toBe(true);
    const patientContent = readFileSync(patientPath, 'utf8');

    expect(patientContent).toContain('isLocalCameraFallback');
    expect(patientContent).toContain('startFallbackCamera');
    expect(patientContent).toContain('getUserMedia');
    expect(patientContent).toContain("computeValgusDeviation(landmarks2D[23], landmarks2D[25], landmarks2D[27], currentBaseline, 'L')");
    expect(patientContent).toContain("computeValgusDeviation(landmarks2D[24], landmarks2D[26], landmarks2D[28], currentBaseline, 'R')");
  });

  // =========================================================================
  // INTERACTION 9: Clinician Acoustic Guard & Moderator Mute Action
  // =========================================================================

  it('T3-INT.9: Clinician.tsx enforces startAudioMuted: true and provides Mute Patient moderator control', () => {
    const clinicianPath = path.join(CLIENT_DIR, 'src', 'views', 'Clinician.tsx');
    expect(existsSync(clinicianPath)).toBe(true);
    const clinicianContent = readFileSync(clinicianPath, 'utf8');

    expect(clinicianContent).toContain('startAudioMuted: true');
    expect(clinicianContent).toContain('muteParticipant');
    expect(clinicianContent).toContain('Mute Patient');
  });
});
